// ============================================================================
// Pass — durable webhook event forwarding via Vercel Workflow
// Generated by khotan CLI · https://github.com/khotan-data
//
// This file keeps local imports stable while reusing the real builder and types
// from khotan-data/factory. Create per-service pass files (e.g.
// pollinate-to-slack.ts) using pass() to forward verified webhook events to
// another service with durable, retryable workflow steps.
//
// Pass workflows receive a PassContext with the parsed event, event type,
// headers, destVars (variables for the destination plug), and Khotan lifecycle
// IDs. Return a PassRunResult to finalize the linked khotan_runs row.
// ============================================================================

export { pass, passEvent } from "khotan-data/factory";

export type {
  PassConfig,
  PassRegistration,
  PassWorkflow,
  PassWorkflowContext,
  PassWorkflowContext as PassContext,
} from "khotan-data/factory";

// ---------------------------------------------------------------------------
// Usage Example (create a file like webhooks/pollinate-to-slack.ts)
// ---------------------------------------------------------------------------
//
// import { khotanCache } from "khotan-data/factory";
// import { pass, type PassContext } from "./pass";
// import { plug } from "../plugs/plug";
//
// Declare "use step" functions at MODULE TOP LEVEL and pass them serializable
// values only (`ctx` is plain data). Do NOT nest steps inside the "use workflow"
// function — closures over workflow scope cannot be hoisted and fail at runtime.
//
// // Step: top-level, full Node.js access, retried independently.
// async function forwardEvent(ctx: PassContext) {
//   "use step";
//   const cache = khotanCache(ctx, "pollinate-forwarded-events");
//   const eventId = String(ctx.event["id"] ?? "");
//   if (eventId && (await cache.get<boolean>(eventId))) return;
//
//   // Construct destination plug from destVars
//   const slackPlug = plug({
//     name: "slack",
//     baseUrl: "https://hooks.slack.com",
//     authType: "bearer",
//     auth: { bearer: { token: ctx.destVars["token"] ?? "" } },
//   });
//
//   await slackPlug.post("/services/webhook", {
//     body: {
//       text: `Received ${ctx.eventType} event from pollinate`,
//       event: ctx.event,
//     },
//   });
//
//   if (eventId) {
//     await cache.set(eventId, true);
//   }
// }
//
// // Workflow: orchestration only.
// async function pollinateToSlackWorkflow(ctx: PassContext) {
//   "use workflow";
//   await forwardEvent(ctx);
//   return { created: 1 };
// }
//
// export const pollinateToSlack = pass({
//   name: "pollinate-to-slack",
//   to: "slack",
//   events: ["order.created"],
//   idempotencyKey: "id",
//   workflow: pollinateToSlackWorkflow,
// });
//
// Then register in your khotan config:
//
// plugs: [{
//   name: "pollinate",
//   plug: pollinatePlug,
//   wires: [pollinateWire],
//   passes: [pollinateToSlack],
// }]
