import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  listBlocks,
  listComponents,
  isMultiFile,
  type ComponentEntry,
  type ComponentFile,
} from "./registry.js";
import {
  defaultDrizzleSchemaDir,
  resolveDrizzleSchemaDir,
} from "./drizzle-detect.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const STAMP_RE =
  /^\/\/ khotan-template: (?<template>[^\r\n]+)\r?\n\/\/ khotan-template-version: (?<version>[^\r\n]+)\r?\n\/\/ khotan-template-hash: sha256:(?<hash>[a-f0-9]{64})\r?\n(?:\r?\n)?/m;

const LEGACY_GENERATED_MARKER = "Generated by khotan CLI";

export interface TemplateStamp {
  templateName: string;
  version: string;
  hash: string;
}

export interface GeneratedFileDefinition {
  templateName: string;
  relPath: string;
  renderContent: () => string;
}

export type GeneratedFileStatus =
  | "current"
  | "stale"
  | "modified"
  | "legacy"
  | "app-owned"
  | "newer";

export interface GeneratedFileReportItem {
  relPath: string;
  templateName: string;
  status: GeneratedFileStatus;
  owner: "khotan" | "app";
  stamp: TemplateStamp | null;
  currentVersion: string;
  canUpgrade: boolean;
  reason: string;
}

export function readPackageVersion(): string {
  for (const pkgPath of [
    path.resolve(__dirname, "..", "package.json"),
    path.resolve(__dirname, "..", "..", "package.json"),
  ]) {
    try {
      const content = fs.readFileSync(pkgPath, "utf-8");
      const pkg = JSON.parse(content) as { version?: string };
      return pkg.version ?? "0.0.0";
    } catch {
      // Try the next location; bundled CLI and source tests differ by one level.
    }
  }
  return "0.0.0";
}

export function extractTemplateStamp(content: string): TemplateStamp | null {
  const match = STAMP_RE.exec(content);
  const groups = match?.groups;
  if (!groups) return null;
  return {
    templateName: groups["template"] ?? "",
    version: groups["version"] ?? "",
    hash: groups["hash"] ?? "",
  };
}

export function stripTemplateStamp(content: string): string {
  return content.replace(STAMP_RE, "");
}

export function hashTemplateContent(content: string): string {
  return crypto
    .createHash("sha256")
    .update(stripTemplateStamp(content).replace(/\r\n/g, "\n"))
    .digest("hex");
}

export function stampGeneratedContent(
  content: string,
  templateName: string,
  version = readPackageVersion(),
): string {
  const unstamped = stripTemplateStamp(content);
  const stamp =
    `// khotan-template: ${templateName}\n` +
    `// khotan-template-version: ${version}\n` +
    `// khotan-template-hash: sha256:${hashTemplateContent(unstamped)}\n\n`;
  const directiveMatch =
    /^((?:"use client"|'use client'|"use server"|'use server');\r?\n(?:\r?\n)?)/.exec(
      unstamped,
    );

  if (directiveMatch?.[1]) {
    return `${directiveMatch[1]}${stamp}${unstamped.slice(directiveMatch[1].length)}`;
  }

  return `${stamp}${unstamped}`;
}

export function readTemplateContent(
  templatePath: string,
  options: { outputDir?: string } = {},
): string {
  let content = fs.readFileSync(templatePath, "utf-8");
  if (content.includes("__KHOTAN_INGEST_IMPORT__")) {
    const outputDir = options.outputDir ?? "khotan";
    const importBase = outputDir.startsWith("src/")
      ? `@/${outputDir.slice(4)}`
      : `@/${outputDir}`;
    content = content.replace(
      "__KHOTAN_INGEST_IMPORT__",
      `${importBase}/ingests/ingest.example`,
    );
  }
  return content;
}

export function readStampedTemplateContent(
  templatePath: string,
  options: { outputDir?: string; version?: string } = {},
): string {
  return stampGeneratedContent(
    readTemplateContent(templatePath, options),
    path.basename(templatePath),
    options.version,
  );
}

function hasSrcLayout(cwd: string): boolean {
  return fs.existsSync(path.join(cwd, "src", "app"));
}

function toRouteImportPath(fromDir: string, toFile: string): string {
  const withoutExt = toFile.replace(/\.[cm]?tsx?$/, "");
  let relativePath = path
    .relative(fromDir, withoutExt)
    .split(path.sep)
    .join("/");
  if (!relativePath.startsWith(".")) {
    relativePath = `./${relativePath}`;
  }
  return relativePath;
}

export function renderCoreRouteContent(cwd: string, outputDir: string): string {
  const routeDir = path.resolve(
    cwd,
    hasSrcLayout(cwd)
      ? "src/app/api/khotan/[...all]"
      : "app/api/khotan/[...all]",
  );
  const khotanTsPath = path.join(path.resolve(cwd, outputDir), "khotan.ts");
  const khotanImportPath = toRouteImportPath(routeDir, khotanTsPath);
  return (
    `// ============================================================================\n` +
    `// Khotan API Route — catch-all handler for /api/khotan/*\n` +
    `// Generated by khotan CLI · https://github.com/khotan-io/khotan-data\n` +
    `//\n` +
    `// This file binds the generated khotan instance to Next.js route handlers.\n` +
    `// ============================================================================\n` +
    `\n` +
    `import { toNextJsHandler } from "khotan-data/factory";\n` +
    `import khotanData from "${khotanImportPath}";\n` +
    `\n` +
    `export const { GET, POST, PUT, PATCH, DELETE } = toNextJsHandler(\n` +
    `  khotanData.handler,\n` +
    `);\n`
  );
}

export function coreGeneratedFiles(
  cwd: string,
  outputDir: string,
): GeneratedFileDefinition[] {
  const khotanConfigTemplatePath = path.resolve(
    __dirname,
    "templates",
    "khotan-config.ts",
  );
  const khotanRelPath = path.join(outputDir, "khotan.ts");
  const routeRelPath = hasSrcLayout(cwd)
    ? "src/app/api/khotan/[...all]/route.ts"
    : "app/api/khotan/[...all]/route.ts";

  return [
    {
      templateName: "khotan-config.ts",
      relPath: khotanRelPath,
      renderContent: () => readTemplateContent(khotanConfigTemplatePath),
    },
    {
      templateName: "khotan-route.ts",
      relPath: routeRelPath,
      renderContent: () => renderCoreRouteContent(cwd, outputDir),
    },
  ];
}

function resolveOutputBase(
  file: ComponentFile,
  cwd: string,
  outputDir: string,
): string | null {
  switch (file.outputBase) {
    case "components":
      return path.resolve(
        cwd,
        hasSrcLayout(cwd) ? "src/components/khotan" : "components/khotan",
      );
    case "app":
      return path.resolve(
        cwd,
        hasSrcLayout(cwd)
          ? "src/app/api/khotan/[...all]"
          : "app/api/khotan/[...all]",
      );
    case "appRoot":
      return path.resolve(cwd, hasSrcLayout(cwd) ? "src/app" : "app");
    case "lib":
      return path.resolve(cwd, hasSrcLayout(cwd) ? "src/lib" : "lib");
    case "projectRoot":
      return path.resolve(cwd);
    case "agentSkills":
      return null;
    case "outputDir":
    default:
      return path.resolve(cwd, outputDir);
  }
}

function entryFiles(
  entry: ComponentEntry,
  cwd: string,
  outputDir: string,
): GeneratedFileDefinition[] {
  if (isMultiFile(entry)) {
    return entry.files.flatMap((file) => {
      const baseDir = resolveOutputBase(file, cwd, outputDir);
      if (!baseDir) return [];
      const relPath = path.relative(cwd, path.join(baseDir, file.outputFile));
      return [
        {
          templateName: path.basename(file.templatePath),
          relPath,
          renderContent: () =>
            readTemplateContent(file.templatePath, { outputDir }),
        },
      ];
    });
  }

  if (!entry.templatePath || !entry.outputFile) return [];

  const templatePath = entry.templatePath;
  const outputFile = entry.outputFile;
  const outputBase =
    entry.name === "schema"
      ? path.resolve(
          cwd,
          resolveDrizzleSchemaDir(cwd) ?? defaultDrizzleSchemaDir(cwd),
        )
      : path.resolve(cwd, outputDir);
  return [
    {
      templateName: path.basename(templatePath),
      relPath: path.relative(cwd, path.join(outputBase, outputFile)),
      renderContent: () => readTemplateContent(templatePath, { outputDir }),
    },
  ];
}

export function generatedFileDefinitions(
  cwd: string,
  outputDir: string,
): GeneratedFileDefinition[] {
  const byPath = new Map<string, GeneratedFileDefinition>();
  for (const definition of [
    ...coreGeneratedFiles(cwd, outputDir),
    ...listComponents().flatMap((entry) => entryFiles(entry, cwd, outputDir)),
    ...listBlocks().flatMap((entry) => entryFiles(entry, cwd, outputDir)),
  ]) {
    if (!byPath.has(definition.relPath)) {
      byPath.set(definition.relPath, definition);
    }
  }
  return [...byPath.values()].sort((a, b) =>
    a.relPath.localeCompare(b.relPath),
  );
}

function compareVersions(a: string, b: string): number {
  const parse = (version: string) => {
    const [core = ""] = version.replace(/^v/, "").split("-");
    return core.split(".").map((part) => Number.parseInt(part, 10));
  };
  const left = parse(a);
  const right = parse(b);
  for (let i = 0; i < Math.max(left.length, right.length, 3); i += 1) {
    const l = Number.isFinite(left[i]) ? left[i]! : 0;
    const r = Number.isFinite(right[i]) ? right[i]! : 0;
    if (l < r) return -1;
    if (l > r) return 1;
  }
  return a === b ? 0 : a.localeCompare(b);
}

export function analyzeGeneratedFiles(
  cwd: string,
  outputDir: string,
  version = readPackageVersion(),
): GeneratedFileReportItem[] {
  const files: GeneratedFileReportItem[] = [];

  for (const definition of generatedFileDefinitions(cwd, outputDir)) {
    const absPath = path.resolve(cwd, definition.relPath);
    if (!fs.existsSync(absPath)) continue;

    const content = fs.readFileSync(absPath, "utf-8");
    const stamp = extractTemplateStamp(content);
    const currentContent = definition.renderContent();
    const currentHash = hashTemplateContent(currentContent);
    const localHash = hashTemplateContent(content);

    if (!stamp) {
      const isLegacyGenerated = content.includes(LEGACY_GENERATED_MARKER);
      if (!isLegacyGenerated) {
        files.push({
          relPath: definition.relPath,
          templateName: definition.templateName,
          status: "app-owned",
          owner: "app",
          stamp: null,
          currentVersion: version,
          canUpgrade: false,
          reason: "No Khotan generated-file stamp was found.",
        });
        continue;
      }

      files.push({
        relPath: definition.relPath,
        templateName: definition.templateName,
        status: "legacy",
        owner: "khotan",
        stamp: null,
        currentVersion: version,
        canUpgrade: localHash === currentHash,
        reason:
          localHash === currentHash
            ? "Legacy generated file matches the current template and can be stamped."
            : "Legacy generated file has no hash stamp, so local edits cannot be proven safe.",
      });
      continue;
    }

    const unchangedSinceGeneration = stamp.hash === localHash;
    const versionComparison = compareVersions(stamp.version, version);
    if (!unchangedSinceGeneration) {
      files.push({
        relPath: definition.relPath,
        templateName: definition.templateName,
        status: "modified",
        owner: "khotan",
        stamp,
        currentVersion: version,
        canUpgrade: false,
        reason:
          versionComparison < 0
            ? "Generated file is stale and has local edits."
            : "Generated file has local edits.",
      });
      continue;
    }

    if (versionComparison < 0) {
      files.push({
        relPath: definition.relPath,
        templateName: definition.templateName,
        status: "stale",
        owner: "khotan",
        stamp,
        currentVersion: version,
        canUpgrade: true,
        reason: `Generated from ${stamp.version}; current template version is ${version}.`,
      });
      continue;
    }

    if (versionComparison > 0) {
      files.push({
        relPath: definition.relPath,
        templateName: definition.templateName,
        status: "newer",
        owner: "khotan",
        stamp,
        currentVersion: version,
        canUpgrade: false,
        reason: `Generated from newer template version ${stamp.version}.`,
      });
      continue;
    }

    files.push({
      relPath: definition.relPath,
      templateName: definition.templateName,
      status: "current",
      owner: "khotan",
      stamp,
      currentVersion: version,
      canUpgrade: false,
      reason: "Generated file is current.",
    });
  }

  return files;
}

export function renderStampedDefinition(
  definition: GeneratedFileDefinition,
  version = readPackageVersion(),
): string {
  return stampGeneratedContent(
    definition.renderContent(),
    definition.templateName,
    version,
  );
}
