import { Command } from "commander";
import fs from "node:fs";
import path from "node:path";
import { output, resolveOutputDir } from "../cli-api.js";
import {
  analyzeGeneratedFiles,
  generatedFileDefinitions,
  readPackageVersion,
  renderStampedDefinition,
  type GeneratedFileReportItem,
} from "../scaffold.js";

interface UpgradeResultItem {
  relPath: string;
  templateName: string;
  status: string;
  reason: string;
}

interface UpgradeResult {
  updated: UpgradeResultItem[];
  skipped: UpgradeResultItem[];
}

function shouldReplace(
  file: GeneratedFileReportItem,
  opts: { force?: boolean },
): boolean {
  if (file.status === "current") return false;
  if (file.owner !== "khotan") return false;
  if (opts.force) return true;
  return file.canUpgrade;
}

function skipReason(file: GeneratedFileReportItem): string {
  if (file.owner === "app") {
    return "app-owned file has no Khotan generated-file stamp";
  }
  if (file.status === "current") {
    return "already current";
  }
  if (file.status === "modified") {
    return "local edits detected; use --force to replace";
  }
  if (file.status === "legacy") {
    return "legacy generated file has no hash stamp; use --force to replace";
  }
  if (file.status === "newer") {
    return "file was generated by a newer khotan-data version";
  }
  return file.reason;
}

function runUpgrade(opts: {
  cwd: string;
  outputDir: string;
  version: string;
  force?: boolean;
  dryRun?: boolean;
}): UpgradeResult {
  const definitions = new Map(
    generatedFileDefinitions(opts.cwd, opts.outputDir).map((definition) => [
      definition.relPath,
      definition,
    ]),
  );
  const report = analyzeGeneratedFiles(opts.cwd, opts.outputDir, opts.version);
  const result: UpgradeResult = { updated: [], skipped: [] };

  for (const file of report) {
    const definition = definitions.get(file.relPath);
    if (!definition) continue;

    if (!shouldReplace(file, opts)) {
      result.skipped.push({
        relPath: file.relPath,
        templateName: file.templateName,
        status: file.status,
        reason: skipReason(file),
      });
      continue;
    }

    if (!opts.dryRun) {
      const absPath = path.resolve(opts.cwd, file.relPath);
      fs.mkdirSync(path.dirname(absPath), { recursive: true });
      fs.writeFileSync(
        absPath,
        renderStampedDefinition(definition, opts.version),
        "utf-8",
      );
    }

    result.updated.push({
      relPath: file.relPath,
      templateName: file.templateName,
      status: file.status,
      reason: opts.dryRun ? "would update" : "updated",
    });
  }

  return result;
}

function printUpgradeText(result: UpgradeResult, dryRun: boolean): void {
  console.log(dryRun ? "Khotan upgrade (dry run)" : "Khotan upgrade");

  if (result.updated.length > 0) {
    console.log(
      `\n${dryRun ? "Would update" : "Updated"} ${String(result.updated.length)} generated file(s):`,
    );
    for (const file of result.updated) {
      console.log(`  ${file.relPath} [${file.templateName}]`);
    }
  } else {
    console.log("\nNo generated files needed automatic upgrade.");
  }

  const actionableSkipped = result.skipped.filter(
    (file) => file.status !== "current",
  );
  if (actionableSkipped.length > 0) {
    console.log("\nSkipped:");
    for (const file of actionableSkipped) {
      console.log(`  ${file.relPath} [${file.templateName}] - ${file.reason}`);
    }
  }
}

export const upgradeCommand = new Command("upgrade")
  .description("Refresh unchanged Khotan generated scaffold files")
  .option("--json", "Print machine-readable JSON")
  .option("--dry-run", "Report what would change without writing files")
  .option(
    "--force",
    "Replace Khotan-owned generated files even with local edits",
  )
  .option("-y, --yes", "Compatibility flag; upgrade never prompts")
  .action(
    (opts: {
      json?: boolean;
      dryRun?: boolean;
      force?: boolean;
      yes?: boolean;
    }) => {
      void opts.yes;
      const cwd = process.cwd();
      const version = readPackageVersion();
      const outputDir = resolveOutputDir(cwd);
      const upgradeOptions: Parameters<typeof runUpgrade>[0] = {
        cwd,
        outputDir,
        version,
      };
      if (opts.force !== undefined) upgradeOptions.force = opts.force;
      if (opts.dryRun !== undefined) upgradeOptions.dryRun = opts.dryRun;
      const result = runUpgrade(upgradeOptions);

      if (opts.json) {
        output({
          ok: true,
          packageVersion: version,
          outputDir,
          dryRun: opts.dryRun ?? false,
          force: opts.force ?? false,
          ...result,
        });
      } else {
        printUpgradeText(result, opts.dryRun ?? false);
      }
    },
  );
