// ============================================================================
// Khotan API Route — catch-all handler for /api/khotan/*
// Generated by khotan CLI · https://github.com/khotan-io/khotan-data
//
// This file binds the generated khotan instance to Next.js route handlers.
// ============================================================================

import { toNextJsHandler } from "khotan-data/factory";
import khotanData from "../../../../khotan/khotan";

export const { GET, POST, PUT, PATCH, DELETE } = toNextJsHandler(
  khotanData.handler,
);
